package com.finanzaspersonales.presenter.operations;

import lombok.Getter;

public enum OperationName {
  CREATE("Create"), UPDATE("Update"), SHOW("Show"), DELETE("Delete"),
  EXPORT("Export"), BACK("Back");

  //when getName() is called from main, it will refer to what the
  //contstructor built
  @Getter
  private final String name;

  //constructor
  //It will get one of the Enums items (depending on what we specified in main)
  //Eg.(assuming in main) Sysout( Operation.CREATE), will pass on
  //what is next to CREATE, which is "Create"
  //it will assign it to the field above: String name;
  //So the getName() generated by lombok will show that as value
  //So if we are in main and do Sysout(OperationName.CREATE.getName())
  // we will get "Create"
  OperationName(String name) { this.name = name; }


}
